version: "2"

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write
        - (*database/sql.DB).Close
  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
