// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: poll_options.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createPollOption = `-- name: CreatePollOption :one
INSERT INTO poll_options (poll_id, starts_at, duration_minutes, all_day_date, position)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, poll_id, starts_at, duration_minutes, all_day_date, position
`

type CreatePollOptionParams struct {
	PollID          int64
	StartsAt        sql.NullString
	DurationMinutes sql.NullInt64
	AllDayDate      sql.NullString
	Position        int64
}

func (q *Queries) CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PollOption, error) {
	row := q.db.QueryRowContext(ctx, createPollOption,
		arg.PollID,
		arg.StartsAt,
		arg.DurationMinutes,
		arg.AllDayDate,
		arg.Position,
	)
	var i PollOption
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.StartsAt,
		&i.DurationMinutes,
		&i.AllDayDate,
		&i.Position,
	)
	return i, err
}

const deletePollOption = `-- name: DeletePollOption :exec
DELETE FROM poll_options WHERE id = ?1 AND poll_id = ?2
`

type DeletePollOptionParams struct {
	ID     int64
	PollID int64
}

func (q *Queries) DeletePollOption(ctx context.Context, arg DeletePollOptionParams) error {
	_, err := q.db.ExecContext(ctx, deletePollOption, arg.ID, arg.PollID)
	return err
}

const getPollOption = `-- name: GetPollOption :one
SELECT id, poll_id, starts_at, duration_minutes, all_day_date, position FROM poll_options WHERE id = ?1 AND poll_id = ?2
`

type GetPollOptionParams struct {
	ID     int64
	PollID int64
}

func (q *Queries) GetPollOption(ctx context.Context, arg GetPollOptionParams) (PollOption, error) {
	row := q.db.QueryRowContext(ctx, getPollOption, arg.ID, arg.PollID)
	var i PollOption
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.StartsAt,
		&i.DurationMinutes,
		&i.AllDayDate,
		&i.Position,
	)
	return i, err
}

const listPollOptions = `-- name: ListPollOptions :many
SELECT id, poll_id, starts_at, duration_minutes, all_day_date, position FROM poll_options WHERE poll_id = ?1 ORDER BY position, id
`

func (q *Queries) ListPollOptions(ctx context.Context, pollID int64) ([]PollOption, error) {
	rows, err := q.db.QueryContext(ctx, listPollOptions, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollOption
	for rows.Next() {
		var i PollOption
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.StartsAt,
			&i.DurationMinutes,
			&i.AllDayDate,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxPollOptionPosition = `-- name: MaxPollOptionPosition :one
SELECT CAST(COALESCE(MAX(position), -1) AS INTEGER) AS max_position
FROM poll_options WHERE poll_id = ?1
`

func (q *Queries) MaxPollOptionPosition(ctx context.Context, pollID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxPollOptionPosition, pollID)
	var max_position int64
	err := row.Scan(&max_position)
	return max_position, err
}
