// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createSpaceInvitation = `-- name: CreateSpaceInvitation :one
INSERT INTO space_invitations (space_id, email, role, token_hash, invited_by_user_id, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, space_id, email, role, token_hash, invited_by_user_id, expires_at, created_at
`

type CreateSpaceInvitationParams struct {
	SpaceID         int64
	Email           string
	Role            string
	TokenHash       string
	InvitedByUserID int64
	ExpiresAt       string
	CreatedAt       string
}

func (q *Queries) CreateSpaceInvitation(ctx context.Context, arg CreateSpaceInvitationParams) (SpaceInvitation, error) {
	row := q.db.QueryRowContext(ctx, createSpaceInvitation,
		arg.SpaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedByUserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i SpaceInvitation
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSpaceInvitation = `-- name: DeleteSpaceInvitation :exec
DELETE FROM space_invitations WHERE id = ?1 AND space_id = ?2
`

type DeleteSpaceInvitationParams struct {
	ID      int64
	SpaceID int64
}

func (q *Queries) DeleteSpaceInvitation(ctx context.Context, arg DeleteSpaceInvitationParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpaceInvitation, arg.ID, arg.SpaceID)
	return err
}

const deleteSpaceInvitationByEmail = `-- name: DeleteSpaceInvitationByEmail :exec
DELETE FROM space_invitations WHERE space_id = ?1 AND email = ?2
`

type DeleteSpaceInvitationByEmailParams struct {
	SpaceID int64
	Email   string
}

func (q *Queries) DeleteSpaceInvitationByEmail(ctx context.Context, arg DeleteSpaceInvitationByEmailParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpaceInvitationByEmail, arg.SpaceID, arg.Email)
	return err
}

const deleteSpaceMember = `-- name: DeleteSpaceMember :execrows
DELETE FROM space_members WHERE space_id = ?1 AND user_id = ?2
`

type DeleteSpaceMemberParams struct {
	SpaceID int64
	UserID  int64
}

func (q *Queries) DeleteSpaceMember(ctx context.Context, arg DeleteSpaceMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSpaceMember, arg.SpaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMembership = `-- name: GetMembership :one
SELECT role FROM space_members WHERE space_id = ?1 AND user_id = ?2
`

type GetMembershipParams struct {
	SpaceID int64
	UserID  int64
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMembership, arg.SpaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, public_id, slug, name, owner_user_id, created_at, default_timezone, retention_days FROM spaces WHERE id = ?1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id int64) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Slug,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.DefaultTimezone,
		&i.RetentionDays,
	)
	return i, err
}

const getSpaceBySlug = `-- name: GetSpaceBySlug :one
SELECT id, public_id, slug, name, owner_user_id, created_at, default_timezone, retention_days FROM spaces WHERE slug = ?1
`

func (q *Queries) GetSpaceBySlug(ctx context.Context, slug string) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceBySlug, slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Slug,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.DefaultTimezone,
		&i.RetentionDays,
	)
	return i, err
}

const getSpaceInvitationByTokenHash = `-- name: GetSpaceInvitationByTokenHash :one
SELECT id, space_id, email, role, token_hash, invited_by_user_id, expires_at, created_at FROM space_invitations WHERE token_hash = ?1
`

func (q *Queries) GetSpaceInvitationByTokenHash(ctx context.Context, tokenHash string) (SpaceInvitation, error) {
	row := q.db.QueryRowContext(ctx, getSpaceInvitationByTokenHash, tokenHash)
	var i SpaceInvitation
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPollsBySpace = `-- name: ListPollsBySpace :many
SELECT polls.id, polls.public_id, polls.space_id, polls.created_by_user_id, polls.admin_token_hash, polls.title, polls.description, polls.location, polls.video_url, polls.kind, polls.timezone, polls.status, polls.hide_participants, polls.require_voter_email, polls.allow_comments, polls.finalized_option_id, polls.deletes_at, polls.created_at, polls.updated_at, polls.retention_days, polls.reminder_sent_at, users.name AS owner_name
FROM polls
LEFT JOIN users ON users.id = polls.created_by_user_id
WHERE polls.space_id = ?1
ORDER BY polls.created_at DESC
`

type ListPollsBySpaceRow struct {
	Poll      Poll
	OwnerName sql.NullString
}

func (q *Queries) ListPollsBySpace(ctx context.Context, spaceID sql.NullInt64) ([]ListPollsBySpaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPollsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPollsBySpaceRow
	for rows.Next() {
		var i ListPollsBySpaceRow
		if err := rows.Scan(
			&i.Poll.ID,
			&i.Poll.PublicID,
			&i.Poll.SpaceID,
			&i.Poll.CreatedByUserID,
			&i.Poll.AdminTokenHash,
			&i.Poll.Title,
			&i.Poll.Description,
			&i.Poll.Location,
			&i.Poll.VideoUrl,
			&i.Poll.Kind,
			&i.Poll.Timezone,
			&i.Poll.Status,
			&i.Poll.HideParticipants,
			&i.Poll.RequireVoterEmail,
			&i.Poll.AllowComments,
			&i.Poll.FinalizedOptionID,
			&i.Poll.DeletesAt,
			&i.Poll.CreatedAt,
			&i.Poll.UpdatedAt,
			&i.Poll.RetentionDays,
			&i.Poll.ReminderSentAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceInvitations = `-- name: ListSpaceInvitations :many
SELECT id, space_id, email, role, token_hash, invited_by_user_id, expires_at, created_at FROM space_invitations WHERE space_id = ?1 ORDER BY created_at, id
`

func (q *Queries) ListSpaceInvitations(ctx context.Context, spaceID int64) ([]SpaceInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceInvitations, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpaceInvitation
	for rows.Next() {
		var i SpaceInvitation
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedByUserID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceMembers = `-- name: ListSpaceMembers :many
SELECT space_members.role, space_members.created_at AS member_since, users.id, users.public_id, users.email, users.name, users.avatar_url, users.locale, users.timezone, users.created_at, users.personal_space_id
FROM space_members
JOIN users ON users.id = space_members.user_id
WHERE space_members.space_id = ?1
ORDER BY space_members.created_at, users.id
`

type ListSpaceMembersRow struct {
	Role        string
	MemberSince string
	User        User
}

func (q *Queries) ListSpaceMembers(ctx context.Context, spaceID int64) ([]ListSpaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpaceMembersRow
	for rows.Next() {
		var i ListSpaceMembersRow
		if err := rows.Scan(
			&i.Role,
			&i.MemberSince,
			&i.User.ID,
			&i.User.PublicID,
			&i.User.Email,
			&i.User.Name,
			&i.User.AvatarUrl,
			&i.User.Locale,
			&i.User.Timezone,
			&i.User.CreatedAt,
			&i.User.PersonalSpaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesForUser = `-- name: ListSpacesForUser :many
SELECT spaces.id, spaces.public_id, spaces.slug, spaces.name, spaces.owner_user_id, spaces.created_at, spaces.default_timezone, spaces.retention_days, space_members.role
FROM spaces
JOIN space_members ON space_members.space_id = spaces.id
WHERE space_members.user_id = ?1
ORDER BY spaces.created_at, spaces.id
`

type ListSpacesForUserRow struct {
	Space Space
	Role  string
}

func (q *Queries) ListSpacesForUser(ctx context.Context, userID int64) ([]ListSpacesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpacesForUserRow
	for rows.Next() {
		var i ListSpacesForUserRow
		if err := rows.Scan(
			&i.Space.ID,
			&i.Space.PublicID,
			&i.Space.Slug,
			&i.Space.Name,
			&i.Space.OwnerUserID,
			&i.Space.CreatedAt,
			&i.Space.DefaultTimezone,
			&i.Space.RetentionDays,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE space_members SET role = ?1 WHERE space_id = ?2 AND user_id = ?3
`

type UpdateMemberRoleParams struct {
	Role    string
	SpaceID int64
	UserID  int64
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberRole, arg.Role, arg.SpaceID, arg.UserID)
	return err
}

const updateSpaceOwner = `-- name: UpdateSpaceOwner :exec
UPDATE spaces SET owner_user_id = ?1 WHERE id = ?2
`

type UpdateSpaceOwnerParams struct {
	OwnerUserID int64
	ID          int64
}

func (q *Queries) UpdateSpaceOwner(ctx context.Context, arg UpdateSpaceOwnerParams) error {
	_, err := q.db.ExecContext(ctx, updateSpaceOwner, arg.OwnerUserID, arg.ID)
	return err
}

const updateSpaceSettings = `-- name: UpdateSpaceSettings :exec
UPDATE spaces SET name = ?1, default_timezone = ?2, retention_days = ?3
WHERE id = ?4
`

type UpdateSpaceSettingsParams struct {
	Name            string
	DefaultTimezone sql.NullString
	RetentionDays   sql.NullInt64
	ID              int64
}

func (q *Queries) UpdateSpaceSettings(ctx context.Context, arg UpdateSpaceSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSpaceSettings,
		arg.Name,
		arg.DefaultTimezone,
		arg.RetentionDays,
		arg.ID,
	)
	return err
}
