// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (user_id, provider, subject, created_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, user_id, provider, subject, created_at
`

type CreateIdentityParams struct {
	UserID    int64
	Provider  string
	Subject   string
	CreatedAt string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.CreatedAt,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (public_id, slug, name, owner_user_id, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, public_id, slug, name, owner_user_id, created_at
`

type CreateSpaceParams struct {
	PublicID    string
	Slug        string
	Name        string
	OwnerUserID int64
	CreatedAt   string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace,
		arg.PublicID,
		arg.Slug,
		arg.Name,
		arg.OwnerUserID,
		arg.CreatedAt,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Slug,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createSpaceMember = `-- name: CreateSpaceMember :exec
INSERT INTO space_members (space_id, user_id, role, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateSpaceMemberParams struct {
	SpaceID   int64
	UserID    int64
	Role      string
	CreatedAt string
}

func (q *Queries) CreateSpaceMember(ctx context.Context, arg CreateSpaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, createSpaceMember,
		arg.SpaceID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (public_id, email, name, avatar_url, locale, timezone, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, public_id, email, name, avatar_url, locale, timezone, created_at, personal_space_id
`

type CreateUserParams struct {
	PublicID  string
	Email     string
	Name      string
	AvatarUrl sql.NullString
	Locale    string
	Timezone  string
	CreatedAt string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.PublicID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.Locale,
		arg.Timezone,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.PersonalSpaceID,
	)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, user_id, provider, subject, created_at FROM identities WHERE provider = ?1 AND subject = ?2
`

type GetIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentity, arg.Provider, arg.Subject)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, public_id, email, name, avatar_url, locale, timezone, created_at, personal_space_id FROM users WHERE email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.PersonalSpaceID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, name, avatar_url, locale, timezone, created_at, personal_space_id FROM users WHERE id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.PersonalSpaceID,
	)
	return i, err
}

const setUserPersonalSpace = `-- name: SetUserPersonalSpace :exec
UPDATE users SET personal_space_id = ?1 WHERE id = ?2
`

type SetUserPersonalSpaceParams struct {
	PersonalSpaceID sql.NullInt64
	ID              int64
}

func (q *Queries) SetUserPersonalSpace(ctx context.Context, arg SetUserPersonalSpaceParams) error {
	_, err := q.db.ExecContext(ctx, setUserPersonalSpace, arg.PersonalSpaceID, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET name = ?1, avatar_url = ?2 WHERE id = ?3
`

type UpdateUserProfileParams struct {
	Name      string
	AvatarUrl sql.NullString
	ID        int64
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile, arg.Name, arg.AvatarUrl, arg.ID)
	return err
}
